version: '3.1'

services:
    nginx-proxy:
        restart: always
        image: jwilder/nginx-proxy:alpine
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
        environment:
            - DEFAULT_HOST=proxy.example
        depends_on:
            - example
        ports:
            - '3000:80'
    example:
        restart: always
        build: .
        env_file: .env
        environment:
            - VIRTUAL_HOST=proxy.example
        volumes:
            - .:/example
            - node_modules:/example/node_modules
        # logging:
        #     driver: 'fluentd'
        #     options:
        #         fluentd-address: localhost:24224
        #         tag: example
volumes:
    node_modules:
networks:
    default:
        external:
            name: br0
